import json
import os.path
from typing import List
import re

SSL_PATH = "/etc/ssl/certs"
CONFIG_BASENAME = "sites.json"

def load_configuration():
    script_directory = path.dirname(path.realpath(__file__))
    config_filename = path.join(script_directory, CONFIG_BASENAME)

    configuration = Configuration.load(config_filename)
    configuration.fill_missing_ssl_entries()
    return configuration

def domain_matches(specific_domain: str, potentially_wildcard_domain: str):
    # FIXME: there are a lot of edge cases:
    regex = potentially_wildcard_domain.replace('.', '\.').replace('*', '[^.]+')
    return bool(re.match(regex, specific_domain))
    
class Configuration:
    def load(filename):
        with open(filename, 'r') as f:
            raw = json.load(f)
            out_file = raw['out_file']
            ssl_entries = [SSLEntry.from_json(domain_name, entry) for domain_name, entry in raw['ssl'].items()]
            entries = [Entry.from_json(entry) for entry in raw['entries']]
            return Configuration(out_file, ssl_entries, entries)

    def __init__(self, out_file: str, ssl_entries, entries):
        self.out_file = out_file
        self.ssl_entries = ssl_entries
        self.entries = entries

    def get_ssl_by_domain(self, domain_name: str):
        for ssl in self.ssl_entries:
            if domain_matches(domain_name, ssl.domain_name):
                return ssl
        return None

    def fill_missing_ssl_entries(self):
        for entry in self.entries:
            if self.get_ssl_by_domain(entry.domain_name) is None:
                self.ssl_entries.append(SSLEntry.by_domain(entry.domain_name))

    def save(self, filename):
        with open(filename, 'w') as f:
            json.dump(f, {
                'out_file': self.out_file,
                'ssl': [e.to_json() for e in self.ssl_entries],
                'entries': [e.to_json() for e in self.entries]
            })


class SSLEntry:
    def from_json(key: str, data):
        return SSLEntry(key, data['certificate'], data['private'])

    def cert_filename_by_domain(domain_name: str):
        if '*.' in domain_name:
            domain_name = domain_name.replace('*.', '') + '.wildcard'
        return f"{SSL_PATH}/{domain_name}.cert"

    def pem_filename_by_domain(domain_name: str):
        if '*.' in domain_name:
            domain_name = domain_name.replace('*.', '') + '.wildcard'
        return f"{SSL_PATH}/{domain_name}.pem"

    def by_domain(domain_name: str):
        return SSLEntry(domain_name, SSLEntry.cert_filename_by_domain(domain_name), SSLEntry.pem_filename_by_domain(domain_name))

    def __init__(self, domain_name: str, cert_file, pem_file):
        self.domain_name = domain_name
        self.cert_file = cert_file
        self.pem_file = pem_file

    def exists(self):
        return os.path.exists(self.cert_file) and os.path.exists(self.pem_file)

class Entry:
    def from_json(data):
        types = [DockerEntry, RedirectEntry, ReverseProxyEntry]
        for type in types:
            if type.is_suitable(data):
                return type.from_json(data)
        raise Exception(f"Couldn't parse {json.dumps(data)}")

class DockerEntry(Entry):
    def is_suitable(data):
        return 'from_port' in data

    def from_json(data):
        return DockerEntry(data['domain'], data['from_port'], data.get('disabled', False))

    def __init__(self, domain_name: str, port: int, enabled: bool):
        self.domain_name = domain_name
        self.port = port
        self.reverse_proxy = ReverseProxyEntry(domain_name, f'http://127.0.0.1:{port}', enabled)
        self.enabled = enabled

    def create_nginx_config(self):
        pass

    def get_identifier(self):
        return f"AUTOGENERATED DOCKER ENTRY with domain {self.domain_name} -> PORT {self.port}"

    def to_json(self):
        return  {
            'domain': self.domain_name,
            'from_port': self.port
        }

    def to_columns(self):
        # Domain, Type, Data, Enabled
        return [self.domain_name, 'Docker', f'Port {self.port}', self.enabled and 'yes' or 'no']

class RedirectEntry(Entry):
    def is_suitable(data):
        return 'redirect' in data

    def from_json(data):
        return RedirectEntry(data['domain'], data['redirect'], data.get('disabled', False))

    def __init__(self, domain_name: str, redirect_domain: str, enabled: bool):
        self.domain_name = domain_name
        self.redirect_domain = redirect_domain
        self.enabled = enabled

    def get_identifier(self):
        return f"AUTOGENERATED REDIRECT ENTRY with domain {self.domain_name} -> domain {self.redirect_domain}"

    def create_nginx_config(self):
        pass

    def to_json(self):
        return  {
            'domain': self.domain_name,
            'redirect': self.redirect_domain
        }

    def to_columns(self):
        # Domain, Type, Data, Enabled
        return [self.domain_name, 'Redirect', self.redirect_domain, self.enabled and 'yes' or 'no']

class ReverseProxyEntry(Entry):
    def is_suitable(data):
        return 'reverse_proxy' in data

    def from_json(data):
        return ReverseProxyEntry(data['domain'], data['reverse_proxy'], data.get('disabled', False))

    def __init__(self, domain_name: str, url: str, enabled: bool):
        self.domain_name = domain_name
        self.url = url
        self.enabled = enabled

    def create_nginx_config(self):
        pass

    def get_identifier(self):
        return f"AUTOGENERATED REVERSE PROXY ENTRY with domain {self.domain_name} -> url {self.url}"

    def to_json(self):
        return  {
            'domain': self.domain_name,
            'reverse_proxy': self.url
        }

    def to_columns(self):
        # Domain, Type, Data, Enabled
        return [self.domain_name, 'Reverse Proxy', self.url, self.enabled and 'yes' or 'no']