import json
from typing import List, Optional
import re
from os import path

SSL_PATH = "/etc/ssl/certs"
DEFAULT_OUT_FILE = "/etc/nginx/sites-available/00-auto_configuration.conf"


def host_matches(specific_host: str, potentially_wildcard_host: str):
    # FIXME: there are a lot of edge cases:
    regex = potentially_wildcard_host.replace('.', r'\.').replace('*', '[^.]+')
    return bool(re.match(regex, specific_host))

def bautify_config(config):
    config = re.sub(r'^\s*\n', '', config)
    tabsize = len(re.match(r'^(\s*)', config).group(1))
    tabregex = re.compile(r'^\s{0,' + str(tabsize) + '}')
    config = '\n'.join(re.sub(tabregex, '', line) for line in config.split('\n'))
    return re.sub('\n{3,}', '\n', config.strip())

class SSLEntry:
    def from_json(data):
        return SSLEntry(data['host'], data['certificate'], data['private'])

    def cert_filename_by_host(hostname: str):
        if '*.' in hostname:
            hostname = hostname.replace('*.', '') + '.wildcard'
        return f"{SSL_PATH}/{hostname}.cert"

    def pem_filename_by_host(hostname: str):
        if '*.' in hostname:
            hostname = hostname.replace('*.', '') + '.wildcard'
        return f"{SSL_PATH}/{hostname}.pem"

    def by_host(hostname: str):
        return SSLEntry(hostname, SSLEntry.cert_filename_by_host(hostname), SSLEntry.pem_filename_by_host(hostname))

    def __init__(self, hostname: str, cert_file, pem_file):
        self.hostname = hostname
        self.cert_file = cert_file
        self.pem_file = pem_file

    def exists(self):
        return path.exists(self.cert_file) and path.exists(self.pem_file)

    def get_nginx_header(self):
        if not self.exists():
            return f"""
                listen 80;
                listen [::]:80;
            """.strip()
        return f"""
                listen 443 ssl;
                listen [::]:443 ssl;

                ssl_certificate {self.cert_file};
                ssl_certificate_key {self.pem_file};
        """.strip()

    def generate_nginx_config(self):
        if not self.exists():
            return ''
        return f"""
            server {{
                listen 80;
                listen [::]:80;
                
                server_name {self.hostname};
                location / {{
                    return 301 https://{self.hostname};
                }}
            }}
        """

    def to_json(self):
        return {
            'host': self.hostname,
            'certificate': self.cert_file,
            'private': self.pem_file
        }


class Rule:
    def from_json(data):
        types = [DockerRule, RedirectRule, ReverseProxyRule]
        for type in types:
            if type.is_suitable(data):
                return type.from_json(data)
        raise Exception(f"Couldn't parse {json.dumps(data)}")

    def __init__(self, hostname: str, enabled: bool):
        self.hostname = hostname
        self.enabled = enabled

    def is_enabled(self):
        return self.enabled


class DockerRule(Rule):
    def is_suitable(data):
        return 'from_port' in data

    def from_json(data):
        return DockerRule(data['host'], data['from_port'], data.get('enabled', True))

    def __init__(self, hostname: str, port: int, enabled: bool):
        super().__init__(hostname, enabled)
        self.port = port
        self.reverse_proxy = ReverseProxyRule(hostname, f'http://127.0.0.1:{port}', enabled)

    def generate_nginx_config(self, ssl: SSLEntry):
        return self.reverse_proxy.generate_nginx_config(ssl)

    def get_identifier(self):
        return f"AUTOGENERATED DOCKER ENTRY with host {self.hostname} -> PORT {self.port}"

    def to_json(self):
        return  {
            'host': self.hostname,
            'from_port': self.port,
            'enabled': self.enabled
        }

    def to_columns(self):
        # Host, Type, Data, Enabled
        return [self.hostname, 'Docker', f'Port {self.port}', self.enabled and 'yes' or 'no']


class RedirectRule(Rule):
    def is_suitable(data):
        return 'redirect' in data

    def from_json(data):
        return RedirectRule(data['host'], data['redirect'], data.get('enabled', True))

    def __init__(self, hostname: str, redirect_host: str, enabled: bool):
        super().__init__(hostname, enabled)
        self.redirect_host = redirect_host
        self.temporary = True

    def get_identifier(self):
        return f"AUTOGENERATED REDIRECT ENTRY with host {self.hostname} -> host {self.redirect_host}"

    def generate_nginx_config(self, ssl: SSLEntry):
        return f"""
            server {{
                {ssl.get_nginx_header()}

                server_name {self.hostname};

                return {307 if self.temporary else 301} $scheme://{self.redirect_host}$request_uri;
            }}
        """
    

    def to_json(self):
        return  {
            'host': self.hostname,
            'redirect': self.redirect_host,
            'enabled': self.enabled
        }

    def to_columns(self):
        # Host, Type, Data, Enabled
        return [self.hostname, 'Redirect', self.redirect_host, self.enabled and 'yes' or 'no']

class ReverseProxyRule(Rule):
    def is_suitable(data):
        return 'reverse_proxy' in data

    def from_json(data):
        return ReverseProxyRule(data['host'], data['reverse_proxy'], data.get('enabled', True))

    def __init__(self, hostname: str, url: str, enabled: bool):
        super().__init__(hostname, enabled)
        self.url = url

    def generate_nginx_config(self, ssl: SSLEntry):
        return f"""
            server {{
                {ssl.get_nginx_header()}

                server_name {self.hostname};

                location / {{
                    proxy_pass {self.url};
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    proxy_set_header X-Forwarded-Host  $host;

                    # WebSocket support (nginx 1.4)
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                }}
            }}
        """


    def get_identifier(self):
        return f"AUTOGENERATED REVERSE PROXY ENTRY with host {self.hostname} -> url {self.url}"

    def to_json(self):
        return  {
            'host': self.hostname,
            'reverse_proxy': self.url,
            'enabled': self.enabled
        }

    def to_columns(self):
        # Host, Type, Data, Enabled
        return [self.hostname, 'Reverse Proxy', self.url, self.enabled and 'yes' or 'no']



class Configuration:
    def load(filename):
        try:
            with open(filename, 'r') as f:
                raw = json.load(f)
                out_file = raw['out_file']
                ssl_entries = [SSLEntry.from_json(entry) for entry in raw['ssl']]
                rules = [Rule.from_json(entry) for entry in raw['rules']]
                return Configuration(filename, out_file, ssl_entries, rules)
        except:
            return Configuration(filename, DEFAULT_OUT_FILE, [], [])

    def __init__(self, config_file: str, out_file: str, ssl_entries, rules):
        self.config_file = config_file
        self.out_file = out_file
        self.ssl_entries = ssl_entries
        self.rules = rules

    def get_ssl_by_host(self, hostname: str):
        for ssl in self.ssl_entries:
            if host_matches(hostname, ssl.hostname):
                return ssl
        return None

    def get_rule_by_host(self, hostname: str):
        for rule in self.rules:
            if host_matches(hostname, rule.hostname):
                return rule
        return None

    def get_rule_by_port(self, port: int):
        for rule in self.rules:
            if getattr(rule, 'port', -1) == port:
                return rule
        return None

    def fill_missing_ssl_entries(self):
        for entry in self.rules:
            if self.get_ssl_by_host(entry.hostname) is None:
                self.ssl_entries.append(SSLEntry.by_host(entry.hostname))

    def save(self):
        with open(self.config_file, 'w') as f:
            json.dump({
                'out_file': self.out_file,
                'ssl': [e.to_json() for e in self.ssl_entries],
                'rules': [e.to_json() for e in self.rules]
            }, f, indent=4)

    def generate_nginx_config(self):
        return '\n\n'.join(map(bautify_config, [
            "### WARNING: This file is auto generated and is likely to be overwritten. Modifications can get lost. ###",
            "# HTTPS Upgrades:",
            *[e.generate_nginx_config() for e in self.ssl_entries if e.exists()],
            "# Rules:",
            *[e.generate_nginx_config(self.get_ssl_by_host(e.hostname)) for e in self.rules if e.is_enabled()]
        ]))
    
    def apply_to_nginx_config(self):
        with open(self.out_file, 'w') as f:
            f.write(self.generate_nginx_config())

    def add_rule(self, rule: Rule):
        existent_rule = self.get_rule_by_host(rule.hostname)
        if existent_rule:
            self.rules.remove(existent_rule)
        self.rules.append(rule)
        existent_ssl = self.get_ssl_by_host(rule.hostname)
        if existent_ssl is None:
            self.ssl_entries.append(SSLEntry.by_host(rule.hostname))

    def remove_rule(self, hostname: str):
        rule = self.get_rule_by_host(hostname)
        if rule is None:
            raise Exception("rule doesn't exist.")
        existent_ssl = self.get_ssl_by_host(rule.hostname)
        if existent_ssl is not None:
            self.ssl_entries.remove(existent_ssl)
        self.rules.remove(rule)