from .reverse_proxy_rule import ReverseProxyRule
from .rule import Rule


class DockerRule(Rule):
    def is_suitable(data):
        return 'from_port' in data

    def from_json(data):
        return DockerRule(data['host'], data['from_port'], data.get('enabled', True))

    def __init__(self, hostname: str, port: int, enabled: bool):
        super().__init__(hostname, enabled)
        self.port = port
        self.reverse_proxy = ReverseProxyRule(hostname, f'http://127.0.0.1:{port}', enabled)

    def generate_nginx_config(self, ssl):
        return self.reverse_proxy.generate_nginx_config(ssl)

    def get_identifier(self):
        return f"AUTOGENERATED DOCKER ENTRY with host {self.hostname} -> PORT {self.port}"

    def to_json(self):
        return  {
            'host': self.hostname,
            'from_port': self.port,
            'enabled': self.enabled
        }

    def to_columns(self):
        # Host, Type, Data, Enabled
        return [self.hostname, 'Docker', f'Port {self.port}', self.enabled and 'yes' or 'no']

