from .rule import Rule


class RedirectRule(Rule):
    def is_suitable(data):
        return 'redirect' in data

    def from_json(data):
        return RedirectRule(data['host'], data['redirect'], data.get('enabled', True))

    def __init__(self, hostname: str, redirect_host: str, enabled: bool):
        super().__init__(hostname, enabled)
        self.redirect_host = redirect_host
        self.temporary = True

    def get_identifier(self):
        return f"AUTOGENERATED REDIRECT ENTRY with host {self.hostname} -> host {self.redirect_host}"

    def generate_nginx_config(self, ssl):
        return """
            server {
                {ssl_header}

                server_name {hostname};

                return {status_code} $scheme://{redirect_host}$request_uri;
            }
        """.format(
            ssl_header=ssl.get_nginx_header(),
            hostname=self.hostname,
            status_code=307 if self.temporary else 301,
            redirect_host=self.redirect_host,
        )

    def to_json(self):
        return  {
            'host': self.hostname,
            'redirect': self.redirect_host,
            'enabled': self.enabled
        }

    def to_columns(self):
        # Host, Type, Data, Enabled
        return [self.hostname, 'Redirect', self.redirect_host, self.enabled and 'yes' or 'no']

