from .rule import Rule


class ReverseProxyRule(Rule):
    def is_suitable(data):
        return 'reverse_proxy' in data

    def from_json(data):
        return ReverseProxyRule(data['host'], data['reverse_proxy'], data.get('enabled', True))

    def __init__(self, hostname: str, url: str, enabled: bool):
        super().__init__(hostname, enabled)
        self.url = url

    def generate_nginx_config(self, ssl):
        return """
            server {
                {ssl_header}

                server_name {hostname};

                location / {{
                    proxy_pass {url};
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    proxy_set_header X-Forwarded-Host  $host;

                    # WebSocket support (nginx 1.4)
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                }}
            }
        """.format(
            ssl_header=ssl.get_nginx_header(),
            hostname=self.hostname,
            url=self.url,
        )

    def get_identifier(self):
        return f"AUTOGENERATED REVERSE PROXY ENTRY with host {self.hostname} -> url {self.url}"

    def to_json(self):
        return  {
            'host': self.hostname,
            'reverse_proxy': self.url,
            'enabled': self.enabled
        }

    def to_columns(self):
        # Host, Type, Data, Enabled
        return [self.hostname, 'Reverse Proxy', self.url, self.enabled and 'yes' or 'no']

